language: php

cache:
  directories:
    - $HOME/.composer/cache
    - vendor

services:
  - mysql

env:
  global:
    - COMPOSER_ARGS="--no-interaction"
    - OPTIONAL_DEPENDENCIES="doctrine/data-fixtures doctrine/migrations"
    - INCLUDE_OPTIONAL_DEPENDENCIES=true

matrix:
  fast_finish: true
  include:
    - php: 7.2
      env:
        - DEPS=lowest
    - php: 7.2
      env:
        - DEPS=lowest
        - INCLUDE_OPTIONAL_DEPENDENCIES=false
    - php: 7.2
      env:
        - CS_CHECK=true
        - DEPS=locked
        - TEST_COVERAGE=true
    - php: 7.2
      env:
        - CS_CHECK=true
        - DEPS=locked
        - INCLUDE_OPTIONAL_DEPENDENCIES=false
        - TEST_COVERAGE=true
    - php: 7.2
      env:
        - DEPS=latest
    - php: 7.2
      env:
        - DEPS=latest
        - INCLUDE_OPTIONAL_DEPENDENCIES=false
    - php: 7.3
      env:
        - DEPS=lowest
    - php: 7.3
      env:
        - DEPS=lowest
        - INCLUDE_OPTIONAL_DEPENDENCIES=false
    - php: 7.3
      env:
        - DEPS=locked
    - php: 7.3
      env:
        - DEPS=locked
        - INCLUDE_OPTIONAL_DEPENDENCIES=false
    - php: 7.3
      env:
        - DEPS=latest
    - php: 7.3
      env:
        - DEPS=latest
        - INCLUDE_OPTIONAL_DEPENDENCIES=false
    - php: 7.4
      env:
        - DEPS=lowest
    - php: 7.4
      env:
        - DEPS=lowest
        - INCLUDE_OPTIONAL_DEPENDENCIES=false
    - php: 7.4
      env:
        - DEPS=locked
    - php: 7.4
      env:
        - DEPS=locked
        - INCLUDE_OPTIONAL_DEPENDENCIES=false
    - php: 7.4
      env:
        - DEPS=latest
    - php: 7.4
      env:
        - DEPS=latest
        - INCLUDE_OPTIONAL_DEPENDENCIES=false

before_install:
  - mysql -e 'CREATE DATABASE `database`;'

install:
  - travis_retry composer install $COMPOSER_ARGS
  - if [[ $DEPS == 'latest' ]]; then travis_retry composer update $COMPOSER_ARGS ; fi
  - if [[ $DEPS == 'lowest' ]]; then travis_retry composer update --prefer-lowest --prefer-stable $COMPOSER_ARGS ; fi
  - if [[ $INCLUDE_OPTIONAL_DEPENDENCIES == 'false' ]]; then travis_retry composer remove $COMPOSER_ARGS --dev $OPTIONAL_DEPENDENCIES; fi
  - composer show

before_script:
  - rm -Rf .travis/cache
  - cp .travis/config/application.config.php config/application.config.php

script:
  - if [[ $TEST_COVERAGE == 'true' ]]; then composer test-coverage ; else composer test ; fi
  - if [[ $TEST_COVERAGE == 'true' ]]; then php build/coverage-checker.php build/clover.xml 70 ; fi
  - if [[ $CS_CHECK == 'true' ]]; then composer cs-check ; fi
  - cat .travis/run-cli.sh | xargs -L 1 php
  - if [[ $INCLUDE_OPTIONAL_DEPENDENCIES == 'true' ]]; then cat .travis/run-cli-migrations.sh | xargs -L 1 php ; fi

after_script:
  - rm -Rf config/application.config.php

after_success:
  - if [[ $TEST_COVERAGE == 'true' ]]; then bash <(curl -s https://codecov.io/bash) -f ./build/clover.xml; fi

